#! /bin/bash
 
# Generate the contents of a compile_commands.json file for the current
# directory which should be the top of the oper1a repository.
 
OCI_PATH="/mnt/c/instantclient-sdk-windows.x64-12.1.0.2.0/instantclient_12_1/sdk/include"
DB_CONNECTION_INCLUDE=/mnt/c/repository/private_include
PWD=$(pwd)
 
if [[ -z  "$COMPILE_FLAGS" ]]
then
    COMPILE_FLAGS="-I /mnt/c/repository/code/cpp \
        -isystem /usr/include/boost -std=c++17"
fi
 
echo "["
  
for f in $(git ls-files '*.cpp')
do
    echo "{"
    echo "\"directory\": \"${PWD}\","
    echo "\"command\": \"g++ ${COMPILE_FLAGS} -o \\\"${f/%.cpp/.o}\\\" \\\"${f}\\\"\","
    echo "\"file\": \"${f}\""
    echo "}"
    echo ","
done | sed '$d'
  
echo "]"
