#! /bin/bash
 
# Generate the contents of a compile_commands.json file for the current
# directory which should be the top of the oper1a repository

PWD=$(pwd)
 
if [[ -z  "$COMPILE_FLAGS" ]]
then
    COMPILE_FLAGS="-I /home/shkumar/repository/dev/cpp/cppstarter -I /usr/local/include/c++/15.0.0 -isystem /usr/local/lib/gcc/x86_64-pc-linux-gnu/15.0.0/include -isystem /usr/local/lib/gcc/x86_64-pc-linux-gnu/15.0.0/include-fixed \
        -isystem /usr/local/include/boost -std=c++23"
fi
 
echo "["
  
for f in $(git ls-files '*.cpp')
do
    echo "{"
    echo "\"directory\": \"${PWD}\","
    echo "\"command\": \"g++ ${COMPILE_FLAGS} -o \\\"${f/%.cpp/.o}\\\" \\\"${f}\\\"\","
    echo "\"file\": \"${f}\""
    echo "}"
    echo ","
done | sed '$d'
  
echo "]"
